title: Thairux
description: Personal portfolio website
url: "https://thairux.github.io"
baseurl: "/.me"
theme: minima

author:
  name: Thairux
  email: thairux@example.com

social_links:
  github: Thairux
  twitter: thairux

plugins:
  - jekyll-feed
  - jekyll-sitemap
