title: Thairux
description: Personal portfolio website
baseurl: ""
url: "https://thairux.github.io/.me"
theme: minima

author:
  name: Thairux
  email: thairux@example.com

social_links:
  github: Thairux
  twitter: thairux

paginate: 10
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
